### ISSUE TITLE
is this code has not complete?

### ISSUE THREAD

**Issue by haohuancheng** [lucadruda/iotc-nodejs-device-client#1]
Send telemetry
Send telemetry every 3 seconds

**setInterval(() => {
            iotc.sendTelemetry({
                field1: value1,
                field2: value2,
                field3: value3
            }, sendCallback)**

**Comment by haohuancheng** [comment]
and Where is the complete demonstration code for node.js ?

**Comment by lucadruda** [comment]
You can find samples here:
https://github.com/lucadruda/iotc-samples

**Comment by haohuancheng** [comment]
think you! I got it!
