### ISSUE TITLE
Must not contain Control Characters, '$' for "version

### ISSUE THREAD

**Issue by bryanburress** [lucadruda/iotc-nodejs-device-client#4]
Not sure if this is bug or a mistake on my part, but calling  iotc.sendProperty() fails when changing a setting from inside IOT central hub. 

IOT hub change setting sends:
CenterFreq: { value: 332 }, '$version': 13 }
```

on Receiving device:
CenterFreq: { value: 332 }, '$version': 13 }
(node:12058) UnhandledPromiseRejectionWarning: Error: Property or Tag name has invalid characters. Error in Property/Tag $version. Must not contain Control Characters, '.', '$'

//code which breaks when recieved from IOTHub setting change
iotc.on('SettingsUpdated', (val) => {
            console.log(val)
            Object.keys(val).forEach(setting => {
                iotc.sendProperty({
                    [setting]: {
                        status: 'completed',
                        desiredVersion: val.$version,
                        message: 'whatever'
                    }
                });
            });
        })

```

**Comment by lucadruda** [comment]
could you please post some logs?
set loglevel to ALL and post here. I can take a look.

**Comment by lucadruda** [comment]
also noticed you're missing the "value" item to sync your setting.
The setting object must contain a "value" field with the same value in val.
So it becomes like:
`
iotc.sendProperty({
            [setting]: {
                status: 'completed',
                desiredVersion: val.$version,
                message: 'whatever',
                value: val[setting].value
            }
`

**Comment by lucadruda** [comment]
you also probably need to skip setting with name '$version' until fix is merged for control characters

**Comment by lucadruda** [comment]
Closed for inactivity
